# Generated by Django 5.0.3 on 2024-03-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_min'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='film',
            name='film',
            field=models.CharField(max_length=1000),
        ),
    ]
